pub mod account_profile;
pub mod agent;
pub mod app;
pub mod artifacts;
pub mod attachment;
pub mod capability;
pub mod config;
pub mod connector;
pub mod credential;
pub(crate) mod debug_trace;
pub(crate) mod durable_prompt_state;
pub(crate) mod durable_snapshot;
pub mod durable_state;
pub(crate) mod env_lock;
pub mod error;
pub(crate) mod event_connection;
pub mod execution_lease;
pub mod extension;
pub(crate) mod git_observer;
pub(crate) mod git_worktree_placement;
pub mod history;
pub mod history_archive;
pub mod io;
pub mod local;
pub mod logging;
pub mod managed_bootstrap;
pub mod managed_context;
pub mod mcp;
pub(crate) mod prompt_assembly;
pub mod prompt_transcript;
pub mod provider;
pub(crate) mod provider_output_policy;
pub mod pty;
mod publication_provider_accounts;
pub mod runtime;
pub mod runtime_transport;
pub mod scheduler;
pub mod script;
pub mod secret;
pub mod session;
pub mod session_history_page;
pub mod skill;
pub mod slice;
pub mod slice_provider_auth;
pub mod terminal;
pub mod transport;
pub mod workflow_code;
pub(crate) mod workflow_publication_requirements;
pub(crate) mod workspace_live_sync_ignore;
pub(crate) mod workspace_live_sync_journal;

pub use app::DaemonApp;
pub use config::DaemonConfig;
pub use error::DaemonError;

#[cfg(test)]
mod lib_tests;
#[cfg(test)]
pub(crate) mod test_support;
