use super::*;

#[rustfmt::skip]
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub enum LocalDaemonResponse {
    SessionCreated { session: RuntimeSession, agent: AgentInstance, },
    SessionAttached { attachment: RuntimeAttachment, },
    SessionDetached { attachment: RuntimeAttachment, },
    SessionMembersListed { members: Vec<SessionMember>, invites: Vec<SessionInvite>, },
    SessionInviteCreated { invite: SessionInviteRecord, session: RuntimeSession, },
    SessionInviteJoined { member: SessionMember, session: RuntimeSession, },
    SessionInviteRevoked { invite: SessionInvite, session: RuntimeSession, },
    WorkspaceLinkCreated { link: WorkspaceLinkDefinition, session: RuntimeSession, },
    WorkspaceLinksListed { links: Vec<WorkspaceLinkDefinition>, },
    WorkspaceLinkShown { link: WorkspaceLinkDefinition, },
    WorkspaceLinkAttached { link: WorkspaceLinkDefinition, attachment: WorkspaceLinkAttachment, session: RuntimeSession, },
    WorkspaceLinkDetached { link: WorkspaceLinkDefinition, detached: Vec<WorkspaceLinkAttachment>, session: RuntimeSession, },
    WorkspaceLiveSyncStatus { status: WorkspaceLiveSyncStatus, },
    WorkspaceLiveSyncModeUpdated {
        session: RuntimeSession,
        #[serde(default, skip_serializing_if = "Vec::is_empty")]
        effects: Vec<UserConfigMutationEffect>,
    },
    ProviderRunLaunched { provider_run: RuntimeProviderRun, },
    NativeProviderInteractionResolved { resolution: NativeProviderInteractionResolution, },
    ProviderRunLaunchAccepted { provider_run: RuntimeProviderRun, },
    ProviderRunsLaunchAccepted { provider_runs: Vec<ProviderRunBatchLaunchResult>, failures: Vec<BatchOperationFailure>, },
    ProjectsListed { projects: Vec<RuntimeProject>, },
    ProjectRenamed { project: RuntimeProject, },
    ProjectWorkspacesUpdated { project: RuntimeProject, },
    ProjectArchived { project: RuntimeProject, sessions: Vec<RuntimeSession>, },
    ProjectDeleted { project: RuntimeProject, sessions: Vec<RuntimeSession>, },
    ProjectRestored { project: RuntimeProject, sessions: Vec<RuntimeSession>, },
    SessionsListed { sessions: Vec<RuntimeSession>, },
    SessionResolved { session: RuntimeSession, },
    SessionState {
        session: RuntimeSession,
        agent_activity: BTreeMap<String, crate::runtime::projection::AgentRuntimeActivity>,
        #[serde(default)]
        agent_activity_revision: u64,
    },
    RoomEnvironmentState { environment: crate::session::RoomEnvironmentSnapshot, },
    RoomEnvironmentSlice { binding: Option<RoomEnvironmentSliceBinding>, },
    RoomEnvironmentScreenshotCaptured { artifact: RoomEnvironmentScreenshotArtifact, },
    RoomEnvironmentScreenshotChunk { chunk: RoomEnvironmentScreenshotChunk, },
    RoomEnvironmentEvents { replay: crate::session::EnvironmentReplay, },
    RoomEnvironmentActionHistoryListed { page: crate::session::EnvironmentActionHistoryPage, },
    RoomEnvironmentUpdated { environment: crate::session::RoomEnvironmentSnapshot, },
    RoomEnvironmentTakeoverUpdated { outcome: crate::session::TakeoverOutcome, environment: crate::session::RoomEnvironmentSnapshot, },
    RoomEnvironmentInputReleased { environment: crate::session::RoomEnvironmentSnapshot, },
    RoomEnvironmentActionSubmitted { action_id: String, environment: crate::session::RoomEnvironmentSnapshot, },
    RoomEnvironmentClipboardRead { content: RoomEnvironmentClipboardText, },
    RoomEnvironmentActionCancellationUpdated { outcome: crate::session::ActionCancellationOutcome, environment: crate::session::RoomEnvironmentSnapshot, },
    MetaagentTaskUpdated {
        session: RuntimeSession,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        task: Option<crate::session::MetaagentTask>,
    },
    MetaagentEventsListed { events: Vec<serde_json::Value>, },
    MetaagentCommandsSearched { commands: Vec<serde_json::Value>, },
    MetaagentTurnOverview { overview: serde_json::Value, },
    MetaagentTurnBlob { blob: serde_json::Value, },
    MetaagentEventRead { event: serde_json::Value, },
    MetaagentEventsAcked { acked: Vec<serde_json::Value>, },
    TerminalCommandCatalog { catalog: TerminalCommandCatalog, },
    DaemonHealth { projection: DaemonHealthProjection, },
    DebugBundleExported {
        bundle_dir: String,
        manifest_path: String,
        logs_path: String,
        log_root: String,
        record_count: usize,
        limit: usize,
    },
    ProviderRun { provider_run: RuntimeProviderRun, },
    ProviderRunSelectionUpdated { provider_run: RuntimeProviderRun, },
    ProviderCatalog { catalog: OpenCodeProviderCatalog, },
    ProviderCommandCatalogs { catalogs: BTreeMap<String, ProviderCommandCatalog>, },
    McpServerInstalled { mcp: CharioxMcpServerConfig, path: PathBuf, },
    McpServerUpdated { mcp: CharioxMcpServerConfig, path: PathBuf, },
    McpServerUninstalled { name: String, path: PathBuf, },
    McpServersImported { outcome: McpImportOutcome, },
    ProviderCapabilitiesImported { report: ProviderCapabilityImportReport, },
    McpServer { mcp: CharioxMcpServerConfig, },
    McpServersListed { mcps: Vec<CharioxMcpServerConfig>, },
    EnvironmentRegistered { environment: CharioxEnvironmentConfig, path: PathBuf, },
    EnvironmentRemoved { name: String, path: PathBuf, },
    Environment { environment: CharioxEnvironmentConfig, },
    EnvironmentsListed { environments: Vec<CharioxEnvironmentConfig>, },
    ScriptValidated { script: CharioxScriptMetadata, },
    ScriptRegistered { script: CharioxScriptMetadata, path: PathBuf, },
    ScriptRemoved { script: CharioxScriptMetadata, path: PathBuf, },
    Script { script: CharioxScriptMetadata, },
    ScriptsListed { scripts: Vec<CharioxScriptMetadata>, },
    CredentialRegistered { credential: UserCredentialConfig, path: PathBuf, },
    CredentialUpserted { credential: UserCredentialConfig, path: PathBuf, },
    CredentialRemoved { credential: UserCredentialConfig, path: PathBuf, },
    Credential { credential: UserCredentialConfig, },
    CredentialsListed { credentials: Vec<UserCredentialConfig>, },
    ConnectorRegistered { connector: CharioxConnectorDefinition, path: PathBuf, },
    ConnectorUpserted { connector: CharioxConnectorDefinition, path: PathBuf, },
    ConnectorAdapterRegistered { adapter: CharioxConnectorAdapterDefinition, path: PathBuf, },
    ConnectorAdapterRemoved { adapter: CharioxConnectorAdapterDefinition, path: PathBuf, },
    ConnectorAdapter { adapter: CharioxConnectorAdapterDefinition, },
    ConnectorAdaptersListed { adapters: Vec<CharioxConnectorAdapterDefinition>, },
    ConnectorRemoved { connector: CharioxConnectorDefinition, path: PathBuf, },
    Connector { connector: CharioxConnectorDefinition, },
    ConnectorsListed { connectors: Vec<CharioxConnectorDefinition>, },
    ConnectorTested { execution: ConnectorExecution, },
    Skill { skill: CharioxSkillMetadata, },
    SkillInstalled { skill: CharioxSkillMetadata, path: PathBuf, },
    SkillUpserted { skill: CharioxSkillMetadata, path: PathBuf, },
    SkillUpdated { skill: CharioxSkillMetadata, path: PathBuf, },
    SkillUninstalled { skill: CharioxSkillMetadata, path: PathBuf, },
    SkillsImported { outcome: SkillImportOutcome, },
    SkillsListed { skills: Vec<CharioxSkillMetadata>, },
    RelayStatus { status: RelayStatus, },
    RelayConfigured { status: RelayStatus, },
    CloudRelayStatus { profile: Option<CloudRelayProfile>, },
    CloudRelayLoginStarted { login: CloudRelayLoginStart, },
    CloudRelayLoginPolled { result: CloudRelayLoginPoll, },
    CloudRelayLoggedOut,
    CloudRelayClientPaired { profile: CloudRelayProfile, },
    CloudRelayMachinePaired { profile: CloudRelayProfile, },
    CloudRelayConnected { status: RelayStatus, profile: CloudRelayProfile, token: CloudRelayRuntimeToken, },
    CloudRelayClientTokenIssued { profile: CloudRelayProfile, token: CloudRelayRuntimeToken, },
    KernelClientConnectionResolved { connection: KernelClientConnection, },
    CloudSessionInviteCreated { invite: CloudSessionInvite, },
    CloudSessionInviteShown { invite: CloudSessionInviteDetails, },
    CloudSessionInviteAccepted { acceptance: CloudSessionInviteAcceptance, },
    CloudSessionInviteRevoked { invite_id: String, status: String, },
    CloudSessionMembersListed { session_id: String, members: Vec<CloudSessionMember>, },
    CloudCollaboratorsListed { collaborators: Vec<CloudCollaborator>, },
    UserConfig { path: PathBuf, config: CharioxUserConfig, },
    UserConfigSchema { entries: Vec<crate::config::UserConfigSchemaEntry>, },
    UserConfigUpdated {
        path: PathBuf,
        config: CharioxUserConfig,
        #[serde(default, skip_serializing_if = "Vec::is_empty")]
        effects: Vec<UserConfigMutationEffect>,
    },
    CredentialSecretStored { key: String, },
    CredentialSecretDeleted { key: String, },
    CredentialVaultStatus { status: crate::secret::CharioxVaultUnlockStatus, },
    CredentialVaultLocked { status: crate::secret::CharioxVaultUnlockStatus, },
    CredentialVaultManaged { status: crate::secret::CharioxVaultUnlockStatus, action: String, },
    ManagedEnvironmentCatalog { catalog: ManagedEnvironmentCatalog, },
    ManagedEnvironment { environment: ManagedEnvironmentSummary, },
    ManagedEnvironmentContextTransferPrepared { ticket: crate::managed_context::outbound_service::ManagedContextTransferTicket, },
    ManagedEnvironmentCreated { result: ManagedEnvironmentResult, },
    ManagedEnvironmentLifecycleRequested { result: ManagedEnvironmentResult, },
    ManagedContextTransferStarted { status: crate::managed_context::outbound_service::ManagedContextOutboundOperationStatus, },
    ManagedContextTransferStatus { status: crate::managed_context::outbound_service::ManagedContextOutboundOperationStatus, },
    ManagedContextLaunchTarget { target: ManagedContextLaunchTarget, },
    SlicesListed { slices: Vec<SliceRecord>, },
    SliceCreated { slice: SliceRecord, },
    Slice { slice: SliceRecord, },
    SliceStarted { slice: SliceRecord, },
    SliceStopped { slice: SliceRecord, },
    SliceDeleted { slice: SliceRecord, },
    SliceProviderAuthImported { slice: SliceRecord, provider: String, status: String, },
    SliceProviderAuthRemoved { slice: SliceRecord, provider: String, status: String, },
    SliceProviderLoginStarted { slice: SliceRecord, login: SliceProviderLoginStart, },
    SliceDisplayEndpoint { endpoint: SliceDisplayEndpoint, },
    SliceLogs { slice: SliceRecord, entries: Vec<SliceLogEntry>, },
    SliceStateSaved { slice: SliceRecord, state: crate::slice::SliceSavedStateRecord, },
    SliceStateStatus { slice: SliceRecord, state: Option<crate::slice::SliceSavedStateRecord>, },
    SliceStateReset { slice: SliceRecord, removed_state: Option<crate::slice::SliceSavedStateRecord>, },
    SliceBackupCreated { slice: SliceRecord, backup: crate::slice::SliceBackupRecord, instructions: String, },
    SliceBackupRestored { slice: SliceRecord, backup: crate::slice::SliceBackupRecord, },
    RemoteMachinesListed { machines: Vec<RemoteMachineRecord>, },
    RemoteMachineKernelsListed { machine_ref: String, kernels: Vec<RelayKernelPresence>, },
    WaitingRoomInventory { snapshot: WaitingRoomInventorySnapshot, },
    WaitingRoomPublicSnapshot { snapshot: WaitingRoomPublicSnapshot, },
    ExternalProviderSessionsListed { page: ExternalProviderSessionPage, },
    ExternalProviderSessionsRefreshed { page: ExternalProviderSessionPage, },
    ExternalProviderSessionImported {
        session: RuntimeSession,
        agent: AgentInstance,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        provider_run: Option<RuntimeProviderRun>,
    },
    ExternalProviderAgentImported {
        session: RuntimeSession,
        agent: AgentInstance,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        provider_run: Option<RuntimeProviderRun>,
    },
    WorkspaceDirectoriesSearched { directories: Vec<String>, },
    WorkspaceDirectoryCreated { directory: String, },
    WorkspaceWorktreesListed { workspace_id: String, worktrees: Vec<WorkspaceWorktreeRecord>, },
    WorkspaceWorktreeCreated { workspace_id: String, worktree: WorkspaceWorktreeRecord, },
    WorkspaceWorktreeDeleted { workspace_id: String, worktree_id: String, path: String, },
    WorkspacePullRequestCreated { pull_request: WorkspacePullRequestRecord, },
    WorkspaceGitOverview { overview: WorkspaceGitOverview, },
    WorkspaceFilesListed { listing: WorkspaceRepoFileListing, },
    WorkspaceFileContent { content: WorkspaceFileContent, },
    WorkspaceFileContentNotModified {
        workspace_id: String,
        worktree_id: String,
        path: String,
        fingerprint: String,
        generated_at_ms: u64,
    },
    AgentUtilityCompleted { result: AgentUtilityResult, },
    WorkspaceCommitMessageGenerated { message: String, },
    WorkspaceGitActionCompleted { result: WorkspaceGitActionResult, },
    RemoteMachineApproved { machine: RemoteMachineRecord, },
    RemoteMachineForgotten { machine: RemoteMachineRecord, },
    RemoteMachineRenamed { machine: RemoteMachineRecord, },
    PairingInviteCreated { invite: PairingInviteRecord, },
    PairingInviteJoined { pairing: PairingJoinRecord, },
    TerminalPairingLinkCreated { pairing: TerminalPairingLinkRecord, },
    TerminalPairingLinkJoined { terminal: TerminalRecord, pairing: PairingJoinRecord, },
    TerminalsListed { terminals: Vec<TerminalRecord>, },
    PairedClientsListed { clients: Vec<PairedClientRecord>, },
    PairedClientRecorded { client: PairedClientRecord, },
    PairedClientRevoked { client: PairedClientRecord, },
    ProviderAuthStatus { status: ProviderAuthStatus, },
    ProviderLoginStarted { login: ProviderLoginStart, },
    ProviderLoginStatus { login: ProviderLoginStatus, },
    ProviderLoginInputSent { login_id: String, byte_count: usize, },
    ProviderLoginCancelled { login: ProviderLoginStatus, },
    ProviderLogoutStarted { logout: ProviderLoginStart, },
    ProviderLoggedOut { provider: String, account_profile: String, },
    ProviderAccountProfilesListed { profiles: Vec<crate::account_profile::ProviderAccountProfile>, },
    ProviderAccountProfile { profile: crate::account_profile::ProviderAccountProfile, },
    ProviderAccountProfileRemoved { profile: crate::account_profile::ProviderAccountProfile, },
    ProviderAccountProfileDataDeleted { profile: crate::account_profile::ProviderAccountProfile, },
    ProviderAccountCredentialStored { provider: String, account_profile: String, credential_id: String, replaced: bool, },
    ProviderProcessesListed { processes: Vec<ProviderProcessInfo>, },
    ProviderProcessesTornDown { processes: Vec<ProviderProcessInfo>, },
    SessionHistoryOutline { agents: Vec<SessionHistoryOutlineAgent>, },
    SessionHistoryBlobContent { blob_id: String, entries: Vec<SessionHistoryPageEntry>, },
    PromptInputHistory { entries: Vec<PromptInputHistoryEntry>, },
    PromptInputHistoryRecorded { entry: PromptInputHistoryEntry, },
    PromptSettingsListed { settings: Vec<crate::prompt_assembly::PromptSettingRecord>, },
    PromptSetting { setting: crate::prompt_assembly::PromptSettingRecord, },
    PromptSettingPreview { id: String, markdown: String, variables: BTreeMap<String, String>, },
    PromptSettingsReset { settings: Vec<crate::prompt_assembly::PromptSettingRecord>, },
    AgentPromptScheduleCreated { schedule: crate::session::AgentPromptSchedule, session: RuntimeSession, },
    AgentPromptScheduleCancelled { schedule: crate::session::AgentPromptSchedule, session: RuntimeSession, },
    RecallEvents { events: Vec<HistoryEvent>, next_sequence: Option<u64>, },
    SemanticRecallEvents {
        results: Vec<SemanticRecallMatch>,
        next_cursor: Option<String>,
        unavailable_reason: Option<String>,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        answer: Option<String>,
    },
    RuntimeNotices { notices: Vec<RuntimeNoticeRecord>, },
    InteractionResponded { interaction_id: String, session: RuntimeSession, },
    DeploymentCredentialEnrollmentArmed {
        enrollment_id: String,
        profile_id: String,
        target_version: u64,
        session_id: String,
        agent_id: String,
        expires_at_ms: u64,
    },
    CredentialEnrollmentInteractionResolved {
        status: CredentialEnrollmentInteractionStatus,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        callback: Option<CredentialEnrollmentCallback>,
    },
    PromptSubmitted {
        outcome: PromptSubmissionOutcome,
        session: RuntimeSession,
        agent_activity: BTreeMap<String, crate::runtime::projection::AgentRuntimeActivity>,
        #[serde(default)]
        agent_activity_revision: u64,
    },
    PromptsSubmitted {
        results: Vec<PromptBatchSubmissionResult>,
        failures: Vec<BatchOperationFailure>,
        session: RuntimeSession,
        agent_activity: BTreeMap<String, crate::runtime::projection::AgentRuntimeActivity>,
        #[serde(default)]
        agent_activity_revision: u64,
    },
    PromptCompleted { completion: PromptCompletion, },
    PromptCancelled { cancellation: PromptCancellation, },
    QueuedPromptSteered {
        prompt: PromptQueueItem,
        session: RuntimeSession,
        agent_activity: BTreeMap<String, crate::runtime::projection::AgentRuntimeActivity>,
        #[serde(default)]
        agent_activity_revision: u64,
    },
    QueuedPromptCancelled {
        prompt: PromptQueueItem,
        session: RuntimeSession,
        agent_activity: BTreeMap<String, crate::runtime::projection::AgentRuntimeActivity>,
        #[serde(default)]
        agent_activity_revision: u64,
    },
    QueuedPromptUpdated {
        prompt: PromptQueueItem,
        session: RuntimeSession,
        agent_activity: BTreeMap<String, crate::runtime::projection::AgentRuntimeActivity>,
        #[serde(default)]
        agent_activity_revision: u64,
    },
    SessionConfigUpdated { config: SessionConfigState, session: RuntimeSession, },
    AgentConfigUpdated { agent: AgentInstance, session: RuntimeSession, },
    TerminalResized { session_id: String, cols: u16, rows: u16, },
    TerminalInputSent { session_id: String, attachment_id: String, byte_count: usize, },
    TerminalOutput { records: Vec<TerminalOutputRecord>, },
    ShellCommandCompleted { result: RunShellCommandResult, },
    DirectoryTreeRead { result: ReadDirectoryTreeResult, },
    FileRead { result: ReadFileResult, },
    FileEdited { result: EditFileResult, },
    GitInspected { result: InspectGitResult, },
    ScreenshotCaptured { result: CaptureScreenshotResult, },
    FileTransferred { result: StoredTransferArtifact, },
    SessionEnded { session: RuntimeSession, },
    SessionDeleted { session: RuntimeSession, },
    KernelDeleted { kernel_id: String, deleted_sessions: Vec<RuntimeSession>, },
    SessionAliased { session: RuntimeSession, },
    AgentAliased { agent: AgentInstance, session: RuntimeSession, },
    AgentProfileUpdated { agent: AgentInstance, session: RuntimeSession, },
    AgentSpawned { agent: AgentInstance, },
    AgentsSpawned { agents: Vec<AgentInstance>, },
    TurnUndone { result: TurnUndoResult, },
    AgentForked {
        source_agent_id: String,
        agent: AgentInstance,
        provider_run: RuntimeProviderRun,
        session: RuntimeSession,
    },
    AgentMovedToRemote { agent: AgentInstance, },
    AgentMovedToLocal { agent: AgentInstance, },
    RemoteExtensionManifestSynced { agent: AgentInstance, },
    HomeExtensionAuditListed { events: Vec<crate::durable_state::DurableStateEvent>, },
    SliceAuditListed { events: Vec<crate::durable_state::DurableStateEvent>, },
    AgentDestroyed { agent: AgentInstance, },
    AgentFocused { agent: AgentInstance, },
    AgentOutputSeenAcknowledged { session_id: String, agent_id: String, },
    AgentFocusCycled { agent: Option<AgentInstance>, },
    AgentExtensionGranted { agent: AgentInstance, },
    AgentExtensionRevoked { agent: AgentInstance, },
    AgentsListed { agents: Vec<AgentInstance>, },
    WorkflowCreated { workflow: WorkflowDefinition, session: RuntimeSession, },
    WorkflowCodeValidated { result: crate::workflow_code::WorkflowCodeCompileResult, },
    WorkflowCodeApplied { result: crate::workflow_code::WorkflowCodeCompileAndApplyResult, session: RuntimeSession, },
    WorkflowCodeRun { result: crate::workflow_code::WorkflowCodeRunResult, session: RuntimeSession, },
    WorkflowRegistryListed { entries: Vec<crate::workflow_code::WorkflowRegistryEntryMetadata>, },
    WorkflowRegistryEntry { entry: crate::workflow_code::WorkflowRegistryEntryMetadata, },
    WorkflowRegistryEntryAdded { entry: crate::workflow_code::WorkflowRegistryEntryMetadata, },
    WorkflowRegistryEntryDeleted { name: String, path: PathBuf, },
    WorkflowRegistryEntryLoaded {
        entry: crate::workflow_code::WorkflowRegistryEntryMetadata,
        result: crate::workflow_code::WorkflowCodeCompileAndApplyResult,
        session: RuntimeSession,
    },
    WorkflowRegistryEntryRun {
        entry: crate::workflow_code::WorkflowRegistryEntryMetadata,
        result: crate::workflow_code::WorkflowCodeRunResult,
        session: RuntimeSession,
    },
    WorkflowCodeArtifactCreated { artifact: crate::workflow_code::WorkflowCodeArtifact, },
    WorkflowCodeArtifactUpdated { artifact: crate::workflow_code::WorkflowCodeArtifact, },
    WorkflowCodeSourceBound {
        workflow: WorkflowDefinition,
        session: RuntimeSession,
    },
    WorkflowCodeRebuildPreview {
        preview: crate::workflow_code::WorkflowCodeRebuildPreview,
    },
    WorkflowCodeSourceRebuilt {
        preview: crate::workflow_code::WorkflowCodeRebuildPreview,
        result: crate::workflow_code::WorkflowCodeApplyReport,
        session: RuntimeSession,
    },
    WorkflowCodeSourceUpdatePreview {
        preview: crate::workflow_code::WorkflowCodeSourceUpdatePreview,
    },
    WorkflowCodeSourceUpdated {
        preview: crate::workflow_code::WorkflowCodeSourceUpdatePreview,
        workflow: WorkflowDefinition,
        session: RuntimeSession,
    },
    WorkflowCodeArtifact { artifact: crate::workflow_code::WorkflowCodeArtifact, },
    WorkflowCodeArtifactsListed { artifacts: Vec<crate::workflow_code::WorkflowCodeArtifactMetadata>, },
    WorkflowCodeArtifactDeleted { name: String, path: PathBuf, },
    WorkflowCodeArtifactExported { package: crate::workflow_code::WorkflowCodeArtifactPackage, },
    WorkflowCodeArtifactImported { artifact: crate::workflow_code::WorkflowCodeArtifact, },
    WorkflowCodePackageExported { package: crate::workflow_code::WorkflowCodeArtifactPackage, },
    WorkflowCodePackageImported { artifact: crate::workflow_code::WorkflowCodeArtifact, },
    WorkflowCodeSourceExported { export: crate::workflow_code::WorkflowCodeSourceExport, },
    WorkflowAliased { workflow: WorkflowDefinition, session: RuntimeSession, },
    WorkflowsListed { workflows: Vec<WorkflowDefinition>, },
    WorkflowResolved { workflow: WorkflowDefinition, },
    WorkflowPublicationCreated { publication: WorkflowPublicationDefinition, session: RuntimeSession, },
    WorkflowPublicationsListed { publications: Vec<WorkflowPublicationDefinition>, },
    EventGeneratorCatalogPage { page: EventGeneratorCatalogPage, },
    EventGeneratorDetail { detail: EventGeneratorCatalogDetail, },
    EventGeneratorEventsPage { page: EventGeneratorEventPage, },
    EventGeneratorAuthorizationStarted { flow: EventGeneratorAuthorizationFlow, },
    EventGeneratorResourcesPage { page: EventGeneratorResourcePage, },
    EventConnectionsPage { page: EventConnectionPage, },
    EventConnection { connection: EventConnection, },
    EventConnectionAuthorizationStarted { authorization: EventConnectionAuthorization, },
    EventConnectionAuthorizationObserved {
        authorization: EventConnectionAuthorization,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        connection: Option<EventConnection>,
    },
    EventConnectionResourcesPage { page: EventGeneratorResourcePage, },
    EventConnectionTested { result: chariox_event_protocol::AegsConnectionTestEventResponse, },
    EventConnectionDependencies { connection_id: String, dependencies: Vec<WorkflowEventBindingDependency>, },
    EventConnectionRemoved { connection: EventConnection, deactivated_bindings: Vec<WorkflowEventBindingDependency>, },
    WorkflowEventBindingCreated { binding: crate::session::WorkflowEventBinding, session: RuntimeSession, },
    WorkflowEventBindingsListed { bindings: Vec<crate::session::WorkflowEventBinding>, },
    WorkflowEventBindingUpdated { binding: crate::session::WorkflowEventBinding, session: RuntimeSession, },
    WorkflowEventBindingTransferred { binding: crate::session::WorkflowEventBinding, session: RuntimeSession, },
    WorkflowEventBindingTested { delivery_id: String, queued_prompt_id: String, duplicate: bool, session: RuntimeSession, },
    EventDeliveryStatus { status: EventDeliveryStatus, },
    WorkflowPublication { publication: WorkflowPublicationDefinition, },
    WorkflowPublicationPackageExported {
        publication: WorkflowPublicationDefinition,
        package_version: u32,
        package_digest: String,
        package_archive_base64: String,
        package_files: Vec<WorkflowPublicationPackageFile>,
    },
    WorkflowPublicationDisabled { publication: WorkflowPublicationDefinition, session: RuntimeSession, },
    WorkflowPublicationRuntimeControlled {
        publication: WorkflowPublicationDefinition,
        action: WorkflowPublicationRuntimeAction,
        status: String,
        local_url: Option<String>,
        open_url: Option<String>,
        viewer_url: Option<String>,
        process_id: Option<u32>,
        message: Option<String>,
    },
    WorkflowPublicationDeploymentBound {
        publication: Box<WorkflowPublicationDefinition>,
        operation_key: String,
        deployment_id: String,
        release_id: String,
        package_digest: String,
        desired_revision: u64,
        state: String,
        runtime_session_id: Option<String>,
        local_url: Option<String>,
        tunnel_url: Option<String>,
        process_id: Option<u32>,
        replayed: bool,
    },
    WorkflowPublicationEndpointRegistered {
        publication: WorkflowPublicationDefinition,
        open_url: String,
        viewer_url: String,
        access: String,
        expires_at_ms: Option<u64>,
    },
    WorkflowPublicationMaterialized { publication_id: String, session: RuntimeSession, agent_id_map: BTreeMap<String, String>, },
    WorkflowPublicationRuntimeActivated { publication_id: String, runtime_keys: Vec<String>, },
    WorkflowDesignOpAccepted { session: RuntimeSession, event: WorkflowDesignOpForwarded, },
    WorkflowDesignOpRejected {
        session_id: String,
        origin_client_id: String,
        op_id: String,
        message: String,
    },
    WorkflowEndpointCreated { endpoint: WorkflowEndpointDefinition, workflow: WorkflowDefinition, session: RuntimeSession, },
    WorkflowEndpointAliased { endpoint: WorkflowEndpointDefinition, workflow: WorkflowDefinition, session: RuntimeSession, },
    WorkflowEndpointBound { endpoint: WorkflowEndpointDefinition, workflow: WorkflowDefinition, session: RuntimeSession, },
    WorkflowNodeAdded { node: WorkflowNodeDefinition, workflow: WorkflowDefinition, session: RuntimeSession, },
    WorkflowNodeRemoved { node: WorkflowNodeDefinition, workflow: WorkflowDefinition, session: RuntimeSession, },
    WorkflowNodeInstructionsUpdated { node: WorkflowNodeDefinition, workflow: WorkflowDefinition, session: RuntimeSession, },
    WorkflowNodeCanCompleteRunUpdated { node: WorkflowNodeDefinition, workflow: WorkflowDefinition, session: RuntimeSession, },
    WorkflowNodeCanEmitIntermediateOutputUpdated {
        node: WorkflowNodeDefinition,
        workflow: WorkflowDefinition,
        session: RuntimeSession,
    },
    WorkflowNodeWaitForAllInputsUpdated { node: WorkflowNodeDefinition, workflow: WorkflowDefinition, session: RuntimeSession, },
    WorkflowNodeIntermediateOutputSchemaUpdated {
        node: WorkflowNodeDefinition,
        workflow: WorkflowDefinition,
        session: RuntimeSession,
    },
    WorkflowNodeMaxTurnsUpdated { node: WorkflowNodeDefinition, workflow: WorkflowDefinition, session: RuntimeSession, },
    WorkflowEdgeAdded { edge: WorkflowEdgeDefinition, workflow: WorkflowDefinition, session: RuntimeSession, },
    WorkflowEdgeRemoved { edge: WorkflowEdgeDefinition, workflow: WorkflowDefinition, session: RuntimeSession, },
    WorkflowCanvasLayoutUpdated { layout: WorkflowCanvasLayout, workflow: WorkflowDefinition, session: RuntimeSession, },
    WorkflowRunInvoked {
        workflow_run: WorkflowRun,
        workflow: WorkflowDefinition,
        endpoint: WorkflowEndpointDefinition,
        session: RuntimeSession,
    },
    WorkflowPromptEnqueued {
        queued_prompt: WorkflowQueuedPrompt,
        workflow: WorkflowDefinition,
        endpoint: WorkflowEndpointDefinition,
        session: RuntimeSession,
    },
    WorkflowRunsListed {
        workflow_runs: Vec<WorkflowRun>,
        next_cursor: Option<String>,
    },
    WorkflowRun { workflow_run: WorkflowRun, },
    WorkflowRunCancelled { workflow_run: WorkflowRun, session: RuntimeSession, },
    WorkflowRunPaused { workflow_run: WorkflowRun, session: RuntimeSession, },
    WorkflowRunResumed { workflow_run: WorkflowRun, session: RuntimeSession, },
    WorkflowWatchdogCreated {
        watchdog: WorkflowWatchdogDefinition,
        workflow: WorkflowDefinition,
        endpoint: WorkflowEndpointDefinition,
        session: RuntimeSession,
    },
    WorkflowWatchdogsListed { watchdogs: Vec<WorkflowWatchdogDefinition>, },
    WorkflowWatchdogUpdated { watchdog: WorkflowWatchdogDefinition, session: RuntimeSession, },
    WorkflowWatchdogRemoved { watchdog: WorkflowWatchdogDefinition, session: RuntimeSession, },
    WorkflowScheduleCreated {
        schedule: WorkflowScheduleDefinition,
        workflow: WorkflowDefinition,
        endpoint: WorkflowEndpointDefinition,
        session: RuntimeSession,
    },
    WorkflowSchedulesListed { schedules: Vec<WorkflowScheduleDefinition>, },
    WorkflowScheduleUpdated { schedule: WorkflowScheduleDefinition, session: RuntimeSession, },
    WorkflowScheduleRemoved { schedule: WorkflowScheduleDefinition, session: RuntimeSession, },
    WorkflowSchedulePreviewed { preview: WorkflowSchedulePreview, },
    WorkflowFlushContextUpdated { workflow: WorkflowDefinition, session: RuntimeSession, },
    WorkflowRunOutputSchemaUpdated { workflow: WorkflowDefinition, session: RuntimeSession, },
    WorkflowPromptQueuesListed { queues: Vec<WorkflowPromptQueueDefinition>, },
    WorkflowPromptQueueCreated { queue: WorkflowPromptQueueDefinition, session: RuntimeSession, },
    WorkflowPromptQueueUpdated { queue: WorkflowPromptQueueDefinition, session: RuntimeSession, },
    WorkflowPromptQueueRemoved { queue: WorkflowPromptQueueDefinition, session: RuntimeSession, },
    QueuedWorkflowPromptsListed { queued_prompts: Vec<WorkflowQueuedPrompt>, },
    QueuedWorkflowPromptUpdated { queued_prompt: WorkflowQueuedPrompt, session: RuntimeSession, },
    QueuedWorkflowPromptRemoved { queued_prompt: WorkflowQueuedPrompt, session: RuntimeSession, },
    WorkflowPromptQueueCleared { queued_prompts: Vec<WorkflowQueuedPrompt>, session: RuntimeSession, },
    WorkflowHandoffValidated { valid: bool, warning: Option<String>, },
    WorkflowTurnAcknowledged { workflow_run: WorkflowRun, session: RuntimeSession, },
}
