mod api;
mod client;
mod harness;
mod ipc;
pub(crate) mod provider_requests;
#[cfg(test)]
pub(crate) mod test_support;

pub(crate) use api::redact_client_response_value;
pub use api::{
    deployment_credential_enrollment_interaction_id,
    deployment_credential_enrollment_service_subject,
};
pub use api::{
    AbortMetaagentTaskRequest, AcceptCloudSessionInviteRequest, AckMetaagentEventsRequest,
    AckWorkflowTurnRequest, AcknowledgeAgentOutputSeenRequest,
    ActivateWorkflowPublicationRuntimeRequest, AddWorkflowEdgeRequest, AddWorkflowNodeRequest,
    AddWorkflowRegistryEntryFromWorkflowRequest, AddWorkflowRegistryEntryRequest,
    AgentSubstituteAction, AgentUtilityInput, AgentUtilityKind, AgentUtilityOutput,
    AgentUtilityResult, AliasAgentRequest, AliasSessionRequest, AliasWorkflowEndpointRequest,
    AliasWorkflowRequest, AppendNativeProviderOutputBatchItem,
    AppendNativeProviderOutputBatchRequest, AppendNativeProviderOutputRequest,
    ApplyWorkflowCodeArtifactRequest, ApplyWorkflowCodeRequest, ApplyWorkflowDesignOpRequest,
    ApproveRemoteMachineRequest, ArchiveProjectRequest, ArmDeploymentCredentialEnrollmentRequest,
    AttachToSessionRequest, AttachWorkspaceLinkRequest, BatchOperationFailure,
    BindWorkflowCodeSourceRequest, BindWorkflowEndpointRequest,
    BindWorkflowPublicationDeploymentRequest, BrowseEventGeneratorCategoryRequest,
    BrowseEventGeneratorEventsRequest, CancelActivePromptRequest, CancelAgentPromptScheduleRequest,
    CancelProviderLoginRequest, CancelQueuedPromptRequest, CancelRoomEnvironmentActionRequest,
    CancelWorkflowRunRequest, CaptureScreenshotCapabilityRequest, ClearWorkflowPromptQueueRequest,
    CloudCollaborator, CloudRelayLoginPoll, CloudRelayLoginPollStatus, CloudRelayLoginStart,
    CloudRelayProfile, CloudRelayRuntimeToken, CloudRelayStatusRequest, CloudSessionInvite,
    CloudSessionInviteAcceptance, CloudSessionInviteDetails, CloudSessionMember,
    CommitAndPushWorkspaceChangesRequest, CommitWorkspaceChangesRequest, CompletePromptRequest,
    ConfigureRelayRequest, ConnectCloudRelayRequest, ControlWorkflowPublicationRuntimeRequest,
    CreateAgentPromptScheduleRequest, CreateCloudSessionInviteRequest,
    CreateManagedEnvironmentRequest, CreatePairingInviteRequest, CreateSessionInviteRequest,
    CreateSliceBackupRequest, CreateSliceRequest, CreateTerminalPairingLinkRequest,
    CreateWorkflowCodeArtifactRequest, CreateWorkflowEndpointRequest,
    CreateWorkflowEventBindingRequest, CreateWorkflowPromptQueueRequest,
    CreateWorkflowPublicationRequest, CreateWorkflowRequest, CreateWorkflowScheduleRequest,
    CreateWorkflowWatchdogRequest, CreateWorkspaceDirectoryRequest, CreateWorkspaceLinkRequest,
    CreateWorkspacePullRequestRequest, CreateWorkspaceWorktreeRequest,
    CredentialEnrollmentCallback, CredentialEnrollmentInteractionStatus, CycleAgentFocusRequest,
    DeleteCredentialSecretRequest, DeleteKernelRequest, DeleteProjectRequest, DeleteSessionRequest,
    DeleteWorkflowCodeArtifactRequest, DeleteWorkflowRegistryEntryRequest,
    DeleteWorkspaceWorktreeRequest, DestroyAgentRequest, DetachFromSessionRequest,
    DetachWorkspaceLinkRequest, DisableWorkflowPublicationRequest, EditFileCapabilityRequest,
    EndSessionRequest, EventCatalogCategory, EventCatalogFacet, EventCatalogFacetValue,
    EventConnectedResource, EventConnection, EventConnectionAuthorization,
    EventConnectionLifecycleState, EventConnectionPage, EventConnectionScope,
    EventConnectionStatus, EventDeliveryStatus, EventGeneratorActionDefinition,
    EventGeneratorAuthorizationFlow, EventGeneratorCatalogDetail, EventGeneratorCatalogPage,
    EventGeneratorCatalogSummary, EventGeneratorEventDefinition, EventGeneratorEventPage,
    EventGeneratorParty, EventGeneratorResource, EventGeneratorResourcePage,
    ExportDebugBundleRequest, ExportWorkflowCodeArtifactRequest, ExportWorkflowCodePackageRequest,
    ExportWorkflowCodeSourceRequest, ExportWorkflowPublicationPackageRequest, ExtensionKind,
    ExternalProviderSessionCapabilities, ExternalProviderSessionPage,
    ExternalProviderSessionRecord, FocusAgentRequest, ForgetRemoteMachineRequest, ForkAgentRequest,
    GenerateWorkspaceCommitMessageRequest, GetConnectorAdapterRequest, GetConnectorRequest,
    GetCredentialRequest, GetCredentialVaultStatusRequest, GetDaemonHealthRequest,
    GetEnvironmentRequest, GetEventConnectionRequest, GetEventDeliveryStatusRequest,
    GetEventGeneratorCatalogLandingRequest, GetEventGeneratorDetailRequest,
    GetManagedContextLaunchTargetRequest, GetManagedContextTransferStatusRequest,
    GetManagedEnvironmentRequest, GetMcpServerRequest, GetMetaagentTurnBlobRequest,
    GetMetaagentTurnOverviewRequest, GetPromptInputHistoryRequest, GetPromptSettingRequest,
    GetProviderAuthStatusRequest, GetProviderCatalogRequest, GetProviderCommandCatalogsRequest,
    GetProviderLoginStatusRequest, GetProviderRunRequest, GetRoomEnvironmentEventsRequest,
    GetRoomEnvironmentStateRequest, GetScriptRequest, GetSessionHistoryBlobContentRequest,
    GetSessionHistoryOutlineRequest, GetSessionStateRequest, GetSkillRequest,
    GetSliceDisplayEndpointRequest, GetSliceLogsRequest, GetTerminalCommandCatalogRequest,
    GetUserConfigRequest, GetUserConfigSchemaRequest, GetWaitingRoomPublicSnapshotRequest,
    GetWorkflowCodeArtifactRequest, GetWorkflowPublicationRequest, GetWorkflowRegistryEntryRequest,
    GetWorkflowRunRequest, GetWorkspaceFileContentRequest, GetWorkspaceGitOverviewRequest,
    GetWorkspaceLiveSyncStatusRequest, GrantAgentExtensionRequest,
    ImportExternalProviderAgentRequest, ImportExternalProviderSessionRequest,
    ImportMcpServersRequest, ImportProviderCapabilitiesRequest, ImportSkillsRequest,
    ImportSliceProviderAuthRequest, ImportWorkflowCodeArtifactRequest,
    ImportWorkflowCodePackageRequest, InspectGitCapabilityRequest, InstallEventConnectionRequest,
    InstallMcpServerRequest, InstallSkillRequest, InvokeWorkflowEndpointRequest,
    IssueCloudRelayClientTokenRequest, JoinPairingInviteRequest, JoinSessionInviteRequest,
    JoinTerminalPairingLinkRequest, KernelClientConnection, LaunchProviderRunRequest,
    LaunchProviderRunsRequest, ListAgentsRequest, ListCloudCollaboratorsRequest,
    ListCloudSessionMembersRequest, ListConnectorAdaptersRequest, ListConnectorsRequest,
    ListCredentialsRequest, ListEnvironmentsRequest, ListEventConnectionDependenciesRequest,
    ListEventConnectionResourcesRequest, ListEventConnectionsRequest,
    ListEventGeneratorResourcesRequest, ListExternalProviderSessionsRequest,
    ListHomeExtensionAuditRequest, ListManagedEnvironmentCatalogRequest, ListMcpServersRequest,
    ListMetaagentEventsRequest, ListPairedClientsRequest, ListProjectsRequest,
    ListPromptSettingsRequest, ListProviderProcessesRequest, ListQueuedWorkflowPromptsRequest,
    ListRemoteMachineKernelsRequest, ListRemoteMachinesRequest,
    ListRoomEnvironmentActionHistoryRequest, ListScriptsRequest, ListSessionMembersRequest,
    ListSessionsRequest, ListSkillsRequest, ListSliceAuditRequest, ListSlicesRequest,
    ListTerminalsRequest, ListWorkflowCodeArtifactsRequest, ListWorkflowEventBindingsRequest,
    ListWorkflowPromptQueuesRequest, ListWorkflowPublicationsRequest, ListWorkflowRegistryRequest,
    ListWorkflowRunsRequest, ListWorkflowSchedulesRequest, ListWorkflowWatchdogsRequest,
    ListWorkflowsRequest, ListWorkspaceFilesRequest, ListWorkspaceLinksRequest,
    ListWorkspaceWorktreesRequest, LoadWorkflowRegistryEntryRequest, LocalDaemonRequest,
    LocalDaemonResponse, LockCredentialVaultRequest, LogoutCloudRelayRequest,
    LogoutProviderRequest, ManageCredentialVaultRequest, ManagedContextDevelopmentLaunchTarget,
    ManagedContextLaunchTarget, ManagedContextOutboundOperationPhase,
    ManagedContextOutboundOperationStatus, ManagedContextRepositoryLaunchTarget,
    ManagedContextTransferTarget, ManagedContextTransferTicket, ManagedEnvironmentAutoStopPolicy,
    ManagedEnvironmentCatalog, ManagedEnvironmentComputeClassOption, ManagedEnvironmentContextPlan,
    ManagedEnvironmentContextPlanInput, ManagedEnvironmentContextSource,
    ManagedEnvironmentContextSourceOption, ManagedEnvironmentDesiredState,
    ManagedEnvironmentDevelopmentSetup, ManagedEnvironmentGitCredentials,
    ManagedEnvironmentKernelContextSelection, ManagedEnvironmentLifecycleAction,
    ManagedEnvironmentObservedState, ManagedEnvironmentOperationKind,
    ManagedEnvironmentOperationStatus, ManagedEnvironmentOperationSummary,
    ManagedEnvironmentProviderAccountSelection, ManagedEnvironmentProviderAccounts,
    ManagedEnvironmentRepositoryRole, ManagedEnvironmentRepositorySelection,
    ManagedEnvironmentResult, ManagedEnvironmentSummary, MaterializeWorkflowPublicationRequest,
    MoveAgentToLocalRequest, MoveAgentToRemoteRequest, NativeProviderInteractionResolution,
    ObserveEventConnectionAuthorizationRequest, PairCloudRelayClientRequest,
    PairCloudRelayMachineRequest, PairedClientRecord, PairingInviteIntent, PairingInviteRecord,
    PairingJoinRecord, PauseMetaagentTaskRequest, PauseWorkflowRunRequest,
    PollCloudRelayLoginRequest, PollRuntimeNoticesRequest,
    PrepareManagedEnvironmentContextTransferRequest, PreviewPromptSettingRequest,
    PreviewWorkflowScheduleRequest, PromptBatchSubmissionResult, PromptInputHistoryEntry,
    PromptInputHistoryEntryKind, PromptSettingVersion, ProviderCapabilityImportDuplicate,
    ProviderCapabilityImportEntry, ProviderCapabilityImportReport, ProviderCapabilityImportSummary,
    ProviderLoginProcessState, ProviderLoginStatus, ProviderRunBatchLaunchResult,
    PumpTerminalOutputRequest, PushWorkspaceBranchRequest, QueryRecallRequest,
    ReadDirectoryTreeCapabilityRequest, ReadFileCapabilityRequest, ReadMetaagentEventRequest,
    ReadRoomEnvironmentClipboardRequest, RebuildWorkflowCodeSourceRequest,
    ReconnectEventConnectionRequest, RecordPairedClientRequest, RecordPromptInputHistoryRequest,
    RefreshEventConnectionRequest, RefreshExternalProviderSessionsRequest,
    RegisterConnectorAdapterRequest, RegisterConnectorRequest, RegisterCredentialRequest,
    RegisterEnvironmentRequest, RegisterScriptRequest, RegisterWorkflowPublicationEndpointRequest,
    RelayStatus, RelayStatusRequest, ReleaseRoomEnvironmentInputRequest, RemoteMachineRecord,
    RemoteMachineTrustStatus, RemoveConnectorAdapterRequest, RemoveConnectorRequest,
    RemoveCredentialRequest, RemoveEnvironmentRequest, RemoveEventConnectionRequest,
    RemoveQueuedWorkflowPromptRequest, RemoveScriptRequest, RemoveSliceProviderAuthRequest,
    RemoveWorkflowEdgeRequest, RemoveWorkflowNodeRequest, RemoveWorkflowPromptQueueRequest,
    RemoveWorkflowScheduleRequest, RemoveWorkflowWatchdogRequest, RenameProjectRequest,
    RenameRemoteMachineRequest, RequestCredentialEnrollmentInteractionRequest,
    RequestManagedEnvironmentLifecycleRequest, RequestNativeProviderInteractionRequest,
    RequestRoomEnvironmentInputTakeoverRequest, ResetAllPromptSettingsRequest,
    ResetPromptSettingRequest, ResizeTerminalRequest, ResolveKernelClientConnectionRequest,
    ResolveSessionRequest, ResolveWorkflowRequest, RespondToInteractionRequest,
    RestoreProjectRequest, RestoreSliceBackupRequest, ResumeMetaagentTaskRequest,
    ResumeWorkflowRunRequest, RetryRoomEnvironmentRequest, RevokeAgentExtensionRequest,
    RevokeCloudSessionInviteRequest, RevokePairedClientRequest, RevokeSessionInviteRequest,
    RoomEnvironmentBrowserHistoryAction, RoomEnvironmentBrowserTabAction,
    RoomEnvironmentClipboardText, RoomEnvironmentHumanAction, RoomEnvironmentHumanBrowserAction,
    RoomEnvironmentKeyboardInput, RoomEnvironmentPointerButton,
    RoomEnvironmentPointerPositionRequest, RoomEnvironmentViewportRequest, RunAgentUtilityRequest,
    RunShellCapabilityRequest, RunWorkflowCodeArtifactRequest, RunWorkflowCodeRequest,
    RunWorkflowRegistryEntryRequest, SearchEventGeneratorCatalogRequest,
    SearchMetaagentCommandsRequest, SearchRecallRequest, SearchWorkspaceDirectoriesRequest,
    SemanticRecallMatch, SemanticRecallSearchUtilityInput, SemanticSearchRecallMode,
    SemanticSearchRecallRequest, SendProviderLoginInputRequest, SendTerminalInputRequest,
    SessionHistoryOutlineAgent, SessionHistoryOutlineBlob, SessionHistoryOutlineCursor,
    SessionHistoryOutlineTurn, SessionHistoryOutlineTurnLifecycle, SessionInviteRecord,
    SetCredentialSecretRequest, SetProviderAccountCredentialRequest, SetUserConfigValueRequest,
    SetWorkflowEventBindingStatusRequest, SetWorkflowFlushContextRequest,
    SetWorkflowNodeCanCompleteRunRequest, SetWorkflowNodeCanEmitIntermediateOutputRequest,
    SetWorkflowNodeIntermediateOutputSchemaRequest, SetWorkflowNodeMaxTurnsRequest,
    SetWorkflowNodeWaitForAllInputsRequest, SetWorkflowRunOutputSchemaRequest,
    SetWorkflowScheduleEnabledRequest, SetWorkflowWatchdogEnabledRequest,
    SetWorkspaceLiveSyncModeRequest, ShowCloudSessionInviteRequest, ShowWorkspaceLinkRequest,
    SkillInstallSource, SliceCreateBase, SliceRefRequest, SliceStateResetRequest,
    SliceStateSaveMode, SliceStateSaveRequest, SliceStateSaveScope, SliceStateStatusRequest,
    SpawnAgentRequest, SpawnAgentsRequest, SpawnAgentsRequestItem, StartCloudRelayLoginRequest,
    StartEventGeneratorAuthorizationRequest, StartManagedContextTransferRequest,
    StartProviderLoginRequest, StartRoomEnvironmentRequest, StartSliceProviderLoginRequest,
    SteerQueuedPromptRequest, StopRoomEnvironmentRequest, StoreTransferredFileCapabilityRequest,
    SubmitPromptRequest, SubmitPromptsRequest, SubmitPromptsRequestItem,
    SubmitRoomEnvironmentActionRequest, SubmitRoomEnvironmentBrowserActionRequest,
    SyncRemoteExtensionManifestRequest, TeardownProviderProcessesRequest, TerminalCommandCatalog,
    TerminalCommandCatalogExecutionTarget, TerminalCommandCatalogNode,
    TerminalCommandCatalogNodeKind, TerminalCommandCatalogSurface, TerminalPairingLinkRecord,
    TerminalRecord, TerminalType, TestConnectorRequest, TestEventConnectionRequest,
    TestWorkflowEventBindingRequest, TransferWorkflowEventBindingRequest, TurnUndoResult,
    UndoTurnRequest, UninstallMcpServerRequest, UninstallSkillRequest, UnsetUserConfigValueRequest,
    UpdateAgentConfigRequest, UpdateAgentProfileRequest, UpdateAgentSubstitutesRequest,
    UpdateMcpServerRequest, UpdateMetaagentTaskRequest, UpdateProjectWorkspacesRequest,
    UpdatePromptSettingRequest, UpdateProviderRunSelectionRequest, UpdateQueuedPromptRequest,
    UpdateQueuedWorkflowPromptRequest, UpdateRoomEnvironmentPointerRequest,
    UpdateRoomEnvironmentViewportRequest, UpdateSessionConfigRequest, UpdateSkillRequest,
    UpdateWorkflowCanvasLayoutRequest, UpdateWorkflowCodeArtifactRequest,
    UpdateWorkflowCodeSourceFromWorkflowRequest, UpdateWorkflowNodeInstructionsRequest,
    UpdateWorkflowPromptQueueRequest, UpsertConnectorRequest, UpsertCredentialRequest,
    UpsertSkillRequest, UserConfigMutationEffect, UserConfigProviderReloadSummary,
    ValidateScriptRequest, ValidateWorkflowCodeRequest, ValidateWorkflowHandoffRequest,
    WaitingRoomAgentRuntimePlacement, WaitingRoomGitCredentialSummary,
    WaitingRoomInventorySnapshot, WaitingRoomLaunchTarget, WaitingRoomPublicAgentSummary,
    WaitingRoomPublicItemActivitySummary, WaitingRoomPublicProjectSummary,
    WaitingRoomPublicSessionSummary, WaitingRoomPublicSnapshot,
    WaitingRoomPublicWorkflowEdgeSummary, WaitingRoomPublicWorkflowEndpointSummary,
    WaitingRoomPublicWorkflowNodeSummary, WaitingRoomPublicWorkflowSummary,
    WaitingRoomSessionActivitySummary, WorkflowCodePackageExportTarget,
    WorkflowCodeSourceExportTarget, WorkflowDesignEdge, WorkflowDesignEdgePatch,
    WorkflowDesignEndpoint, WorkflowDesignEndpointPatch, WorkflowDesignNode,
    WorkflowDesignNodePatch, WorkflowDesignOp, WorkflowDesignOpForwarded, WorkflowDesignPoint,
    WorkflowDesignSchemaPatch, WorkflowDesignWorkflow, WorkflowDesignWorkflowPatch,
    WorkflowEventBindingDependency, WorkflowPublicationPackageFile,
    WorkflowPublicationRuntimeAction, WorkflowPublicationSnapshot,
    WorkflowPublicationSourceSessionSnapshot, WorkflowSchedulePreview,
    WorkspaceCommitMessageUtilityInput, WorkspaceFileContent, WorkspaceGitActionResult,
    WorkspaceGitChangeTotals, WorkspaceGitCompareRef, WorkspaceGitFileChange, WorkspaceGitOverview,
    WorkspaceLiveSyncConflictSummary, WorkspaceLiveSyncFooterState, WorkspaceLiveSyncGroupStatus,
    WorkspaceLiveSyncIgnoreStatus, WorkspaceLiveSyncStatus, WorkspaceLiveSyncTargetState,
    WorkspaceLiveSyncTargetStatus, WorkspacePullRequestRecord, WorkspaceRepoFileEntry,
    WorkspaceRepoFileListing, WorkspaceWorktreeRecord,
    DEPLOYMENT_CREDENTIAL_ENROLLMENT_SERVICE_SUBJECT_PREFIX, LOCAL_DAEMON_PROTOCOL_VERSION,
};
pub use api::{
    BindRoomEnvironmentSliceRequest, CaptureRoomEnvironmentScreenshotRequest,
    ReadRoomEnvironmentScreenshotChunkRequest, RoomEnvironmentScreenshotArtifact,
    RoomEnvironmentScreenshotChunk, RoomEnvironmentSliceBinding,
};
pub use client::LocalDaemonClient;
pub use harness::{run_local_harness, LocalHarnessReport};
pub use ipc::{run_local_ipc_server, send_local_ipc_request, LocalIpcClient};
